baseURL = 'https://logosblog.com/'
languageCode = 'zh-cn'
title = '𝓛𝓸𝓰𝓸𝓼'
theme = 'hugo-book'

# 启用 Emoji
enableEmoji = true

# 启用 CJK (中日韩) 语言支持，用于准确统计字数
hasCJKLanguage = true


# Hugo-Book 主题配置
[params]
  # 主题颜色：light, dark, auto
  BookTheme = "light"
  
  #右侧目录
  BookToC = true
  
  # 日期格式
  BookDateFormat = '2006-01-02'


# Markdown 配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
	  # 允许 HTML
      unsafe = true  
  
  [markup.highlight]
	# 代码高亮主题,可选：monokai, dracula, github, vim 等
    style = "monokai"  
	# 显示代码行号
    lineNos = true